### ISSUE TITLE
More intrusively warn that you should not install software via ABRoot

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/ABRoot#15]
ABRooting to install software should be a strictly discouraged process as root partitions are very small and system reserved.

To prevent this we should advise against the use of transactions unless strictly necessary (kernel, drivers), even at the cost of becoming more invasive in the user experience. My idea is to ask the user to confirm entry into the shell by typing: "I understand the danger of installing software in root." and provide a direct link to learn about the risks of ABRooting.

```
===============================================================================
PLEASE READ CAREFULLY BEFORE PROCEEDING
===============================================================================
Changes made in the shell will be applied to the future root on next boot on
successful.
Running a command in a transactional shell is meant to be used by advanced users 
for maintenance purposes.

If you ended up here trying to install an application, consider using 
Flatpak/Appimage or Apx (apx install pacakge) instead.

Know the risks of installing software via ABRoot at [link].
Read more about ABRoot at [https://documentation.vanillaos.org/docs/ABRoot/].

If you still want to proceed, type: "I understand the danger of installing software in root."

**Comment by TheEvilSkeleton** [comment]
I suggest requiring a configuration option or an additional file that allows this, rather than having the user type into the terminal in this way. The last thing we want is for Linus to delete Xorg.

So we can have an option (satirically) like `danger=1` or a file named `danger` which is placed in some rw directory. Or (satirically) an option like `you_understand_the_danger_of_installing_software_in_root_i_am_not_responsible_for_a_broken_system_or_you_getting_fired_because_you_deleted_xorg_YOU_are_choosing_to_make_these_modifications_and_if_you_point_the_finger_at_me_for_messing_up_your_system_then_i_will_laugh_at_you=1`.

**Comment by pietrodicaprio** [comment]
> I suggest requiring a configuration option or an additional file that allows this, rather than having the user type into the terminal in this way. The last thing we want is for Linus to delete Xorg.
> 
> So we can have an option like `danger=1` or a file named `danger` which is placed in some rw directory. Or (satirically) an option like `you_understand_the_danger_of_installing_software_in_root_i_am_not_responsible_for_a_broken_system_or_you_getting_fired_because_you_deleted_xorg_YOU_are_choosing_to_make_these_modifications_and_if_you_point_the_finger_at_me_for_messing_up_your_system_then_i_will_laugh_at_you=1`.

what about setting the option (the long version of the key, ofc) after the first time you type the sentence?

**Comment by mirkobrombin** [comment]
I am more for a root mode like Android. Like locking ABRoot entirely then add an option in VSO which shows a modal to unlock ABRoot by also showing an alert on grub. Then if we add a troubleshooting app in the future, we can display this too.

**Comment by TheEvilSkeleton** [comment]
Sure, but you can always limit it users from unintentionally breaking their PC as much as possible, while giving the option for tinkerers to take advantage of this feature.

FWIW, apt does what I suggested with config option from what I understand https://salsa.debian.org/apt-team/apt/-/merge_requests/198. Unless they found a better solution and deprecated this one, I say either a config option or file.

**Comment by iver0** [comment]
There should definitely be an option to turn this off, considering how at times necessary it is to install software this way in Vanilla OS, like for example a non-flatpak terminal emulator or tmux. Unless I'm missing something and you can install them through `apx` but run them in the host instead of a container.

**Comment by mirkobrombin** [comment]
With the next version, a lot of stuff change in ABRoot, the way you install packages, change things, upgrade the system.. this issue can be closed now.
