### ISSUE TITLE
Automate "Version"

### ISSUE THREAD

**Issue by bketelsen** [Vanilla-OS/ABRoot#25]
having Version as a string in main.go and also as a file in the repo root is fragile and error-prone. Automate this somehow - simple github action + goreleaser on tag maybe?

**Comment by taukakao** [comment]
Correct me if I'm wrong but as it stands abroot v2 doesn't have versions but instead a continuous release.

**Comment by kbdharun** [comment]
> Correct me if I'm wrong but as it stands abroot v2 doesn't have versions but instead a continuous release.

The continuous release will be converted to use point release archives upon stable (at that point we will use continuous release in the dev branch of the future release).

Regarding automating releases and uploading of the artifact, I have indeed added a [release action](https://github.com/Vanilla-OS/ABRoot/blob/main/.github/workflows/release.yml) a while ago but it doesn't do what bketesen suggests and we need to define the version manually. I explored Goreleaser action [^1] for ABRoot repo a while ago (feel free to check the commit log of `.github` directory) but it caused some issues with our dependencies and didn't perform the release. So this issue is still up for grabs for someone to work on.

[^1]: We use the same for generating automatic release notes in other repos.
